# Generated by Django 4.1.2 on 2023-09-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
